### ISSUE TITLE
segfault on exit, linux and OSX

### ISSUE THREAD

**Issue by cgadski** [solemnsky/solemnsky#13]
Glenn and xalri both reported a strange segfault coming from some SFML delegate on the ResMan dtor when the client closes. I haven't been able to replicate this myself.

**Comment by CouleeApps** [comment]
Here's a nasty backtrace in case anyone wants to investigate:
[http://pastebin.com/s71ewzeD](http://pastebin.com/s71ewzeD)

**Comment by CouleeApps** [comment]
It seems like it's destructing a stack-allocated sf::Font and getting caught up in the graphics context or something. Not sure if we need to wait to deinit SFML until after the game has been destroyed? That's my initial guess.

**Comment by cgadski** [comment]
this should be fixed in my latest update, where I _cough_ stop using a singleton resource loader

**Comment by cgadski** [comment]
yep, fixed
