### ISSUE TITLE
Wiki failure

### ISSUE THREAD

**Issue by basilevs** [solemnsky/solemnsky#27]
It is impossible to read or edit wiki on https://github.com/solemnsky/solemnsky/wiki.
Any attempt to navigate there results in redirect to project page: https://github.com/solemnsky/solemnsky/

**Comment by cgadski** [comment]
We have no wiki on github currently! We do have the solemnsky-info repository for documentation, status updates and the like though.

**Comment by basilevs** [comment]
Could you disable "Wikis" feature in https://github.com/solemnsky/solemnsky/settings then? The tab on the project page is misleading.

**Comment by cgadski** [comment]
Done, hadn't previously paid any attention to this.
