### ISSUE TITLE
Build Fail on Linux

### ISSUE THREAD

**Issue by rwest202** [solemnsky/solemnsky#28]
I encountered a failure when building the latest version.

``` sh
[ 45%] Building CXX object CMakeFiles/solemnsky.dir/src/engine/sky/participation.cpp.o
In file included from /home/ryan/bin/sky/src/engine/sky/sky.hpp:29:0,
                 from /home/ryan/bin/sky/src/engine/sky/participation.cpp:20:
/home/ryan/bin/sky/src/util/networkedmap.hpp:212:2: error: extra ‘;’ [-Werror=pedantic]
 };
  ^
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/solemnsky.dir/build.make:207: CMakeFiles/solemnsky.dir/src/engine/sky/participation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:116: CMakeFiles/solemnsky.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

When I removed the semicolon on line 212 of networkedmap.hpp the build was successful.

Full log here: http://pastebin.com/gv9KWAM6

**Comment by oldmud0** [comment]
Wow, I can't believe the code is held to such high standards with `-Werror`.

**Comment by CouleeApps** [comment]
@oldmud0 `-Werror -Wextra -pedantic` actually, MagneticDuck is a code quality maniac.

**Comment by oldmud0** [comment]
Well, PR it I guess.

**Comment by cgadski** [comment]
Interesting that my version of clang wasn't catching this. @rwest202 what's your compiler?

**Comment by rwest202** [comment]
gcc 6.1.1

**Comment by cgadski** [comment]
Perhaps I should build with GCC more often. Thanks for the heads-up.

**Comment by oldmud0** [comment]
Clang should have caught that, but it's hard to find any bug reports about it on the mailing lists because all the Gmane links are dead. Rest in peace, Gmane
