### ISSUE TITLE
a parenthesized type followed by an initializer list is a non-standard explicit type conversion

### ISSUE THREAD

**Issue by JeffProgrammer** [solemnsky/solemnsky#3]
The only thing that prevents this from compiling in MSVC 2015 is this:

https://github.com/solemnsky/solemnsky/blob/master/src/base/control.cpp#L102-L103

**Comment by cgadski** [comment]
Now at https://github.com/solemnsky/solemnsky/blob/master/src/ui/frame.cpp#L57

Hm, there are many corners of C++ that have yet escaped my comprehension...

**Comment by cgadski** [comment]
huh, so is there any way to set a a queue to a new queue with exactly one element without writing its explicit constructor plus template variables?
