### ISSUE TITLE
Map file format

### ISSUE THREAD

**Issue by lhallam** [solemnsky/solemnsky#5]
This issue is to track the progress of creating and implementing a map format.

**Comment by lhallam** [comment]
# Altx Format Specification

Altx files are lzma compressed archives used to store map data and resources for Altitude maps.

## Archive Format
- LZMA compressed
  - First 5 bytes are LZMA properties
    - The first is used to get [lc, lp and pb](http://stackoverflow.com/questions/3057171/lzma-compression-settings-details)
      - let `x` be the value of the first byte of the file
      - `lc = x % 9`,  `lp = (x / 9) % 5`,  `pb = (x / 9) / 5`
    - next four are the dictionary size, least significant byte first.
  - followed by 8 bits for the stream size
  - then all the compressed data

The altx file is decompressed and stored as _extract.tmp in the maps cache directory, this binary file is an archive containing the map and all it's resources. Integers use network byte ordering (most significant byte first).
- the file starts with a 32 bit integer for the number of files in the archive
- then a list of file paths (strings)
  - Strings start with 16 bits for the length, followed by 8 bit ascii characters
- and a list of file sizes (?) (32 bit integers)
- the rest of the file is the arcive's content:
- for each file, if it's directory doesn't exist it's created, then the
  file is copied byte by byte to it's destination.

## Altx File layout

File structure of the decompressed archive:
- [map name].alte
- _cache_key.xml
- _config
  - image-descriptors.txt
- _derived/dist
  - .image
    - pck.txt
    - images
      - image-lookup-map.txt
      - p0, p1, p2, ..
  - .sound
    - Contains a couple of seemingly empty XML files

## Resource Packing Format

### pck.txt

A zlib compressed file containing the directory structure.
I'm not sure if reading this will be necessary, as we know which images we have from the alte file and their names from `image-lookup-map.txt`.

### Image Descriptors

Image descriptors contain the wrap mode, filter, and pixel format for images used in the map:
- Wrap modes:  `REPEAT, CLAMP`
- Filter modes:  `LINEAR, NEAREST`
- Pixel formats: `ALPHA8, RGB5, RGBA4, RGBA8, DXT1, DXT1A, DXT3, DXT5`
  - `RGBA8` seems to be the usual format. This is a 32 bit RGBA bitmap with 8 bits per channel.

They're stored in the xml file `_config/image-descriptors.txt`.

## Alte Map Format

**Comment by cgadski** [comment]
I'll be using a very simple custom map format for now, in the future we'll convert some .altx maps.

**Comment by cgadski** [comment]
All done, we have what we need and more.
